languages:
  JavaScript: true
  Python: true

exclude_paths:
- "siteprefs/runtests.py"
- "siteprefs/tests.py"
- "siteprefs/tests/*"
- "siteprefs/migrations/*"
- "siteprefs/south_migrations/*"
- "docs/*"
